package com.example.githubsearch.network

import com.squareup.moshi.Json

data class GithubProperty(
    @Json(name = "total_count") val totalCount: Int,
    @Json(name = "incomplete_results") val incompleteResult: Boolean,
    @Json(name = "items") val items: List<Item>? = null
)

data class Item(
    val id: Int,
    @Json(name = "node_id") val nodeId: String? = null,
    val name: String,
    @Json(name = "full_name") val fullName: String? = null,
    val private: Boolean,
    val owner: Owner,
    @Json(name = "html_url") val htmlUrl: String? = null,
    val description: String? = null,
    val fork: Boolean,
    val url: String? = null,
    @Json(name = "forks_url") val forksUrl: String? = null,
    @Json(name = "keys_url") val keysUrl: String? = null,
    @Json(name = "collaborators_url") val collaboratorsUrl: String? = null,
    @Json(name = "teams_url") val teamsUrl: String? = null,
    @Json(name = "hooks_url") val hooksUrl: String? = null,
    @Json(name = "issue_events_url") val issueEventsUrl: String? = null,
    @Json(name = "events_url") val eventsUrl: String? = null,
    @Json(name = "assignees_url") val assigneesUrl: String? = null,
    @Json(name = "branches_url") val branchesUrl: String? = null,
    @Json(name = "tags_url") val tagsUrl: String? = null,
    @Json(name = "blobs_url") val blobsUrl: String? = null,
    @Json(name = "git_tags_url") val gitTagsUrl: String? = null,
    @Json(name = "git_refs_url") val gitRefsUrl: String? = null,
    @Json(name = "trees_url") val treesUrl: String? = null,
    @Json(name = "statuses_url") val statusesUrl: String? = null,
    @Json(name = "languages_url") val languagesUrl: String? = null,
    @Json(name = "stargazers_url") val stargazersUrl: String? = null,
    @Json(name = "contributors_url") val contributorsUrl: String? = null,
    @Json(name = "subscribers_url") val subscribersUrl: String? = null,
    @Json(name = "subscription_url") val subscriptionUrl: String? = null,
    @Json(name = "commits_url") val commitsUrl: String? = null,
    @Json(name = "git_commits_url") val gitCommitsUrl: String? = null,
    @Json(name = "comments_url") val commentsUrl: String? = null,
    @Json(name = "issue_comment_url") val issueCommentUrl: String? = null,
    @Json(name = "contents_url") val contentsUrl: String? = null,
    @Json(name = "compare_url") val compareUrl: String? = null,
    @Json(name = "merges_url") val mergesUrl: String? = null,
    @Json(name = "archive_url") val archiveUrl: String? = null,
    @Json(name = "downloads_url") val downloadsUrl: String? = null,
    @Json(name = "issues_url") val issuesUrl: String? = null,
    @Json(name = "pulls_url") val pullsUrl: String? = null,
    @Json(name = "milestones_url") val milestonesUrl: String? = null,
    @Json(name = "notifications_url") val notificationsUrl: String? = null,
    @Json(name = "labels_url") val labelsUrl: String? = null,
    @Json(name = "releases_url") val releasesUrl: String? = null,
    @Json(name = "deployments_url") val deploymentsUrl: String? = null,
    @Json(name = "created_at") val createdAt: String? = null,
    @Json(name = "updated_at") val updatedAt: String? = null,
    @Json(name = "pushed_at") val pushedAt: String? = null,
    @Json(name = "git_url") val gitUrl: String? = null,
    @Json(name = "ssh_url") val sshUrl: String? = null,
    @Json(name = "clone_url") val cloneUrl: String? = null,
    @Json(name = "svn_url") val svnUrl: String? = null,
    val homepage: String? = null,
    val size: Int,
    @Json(name = "stargazers_count") val stargazersCount: Int,
    @Json(name = "watchers_count") val watchersCount: Int,
    var language: String? = null,
    @Json(name = "has_issues") val hasIssues: Boolean,
    @Json(name = "has_projects") val hasProjects: Boolean,
    @Json(name = "has_downloads") val hasDownloads: Boolean,
    @Json(name = "has_wiki") val hasWiki: Boolean,
    @Json(name = "has_pages") val hasPages: Boolean,
    @Json(name = "forks_count") val forksCount: Int,
    @Json(name = "mirror_url") val mirrorUrl: String? = null,
    val archived: Boolean,
    val disabled: Boolean,
    @Json(name = "open_issues_count") val openIssuesCount: Int,
    val license: License? = null,
    val forks: Int,
    @Json(name = "open_issues") val openIssues: Int,
    @Json(name = "watchers") val watchers: Int,
    @Json(name = "default_branch") val defaultBranch: String? = null,
    val score: Double
)

data class Owner(
    val login: String,
    val id: Int,
    @Json(name = "node_id") val nodeId: String,
    @Json(name = "avatar_url") val avatarUrl: String,
    @Json(name = "gravatar_id") val gravatarId: String,
    val url: String,
    @Json(name = "html_url") val htmlUrl: String,
    @Json(name = "followers_url") val followersUrl: String,
    @Json(name = "following_url") val followingUrl: String,
    @Json(name = "gists_url") val gistsUrl: String,
    @Json(name = "starred_url") val starredUrl: String,
    @Json(name = "subscriptions_url") val subscriptionsUrl: String,
    @Json(name = "organizations_url") val organizationsUrl: String,
    @Json(name = "repos_url") val reposUrl: String,
    @Json(name = "events_url") val eventsUrl: String,
    @Json(name = "received_events_url") val receivedEventsUrl: String,
    val type: String,
    @Json(name = "site_admin") val siteAdmin: Boolean
)

data class License(
    val key: String,
    val name: String,
    @Json(name = "spdx_id") val spdxId: String,
    val url: String,
    @Json(name = "node_id") val nodeId: String
)